//! The MCP server: a single [`QmpMcpServer`] struct whose `#[tool_router]` impl
//! carries the `#[tool]` methods, and whose `#[tool_handler] impl ServerHandler`
//! advertises them (ADR-0011). This slice is the walking skeleton — one trivial
//! `get_status` tool returning a placeholder — proving the rmcp wiring end to end.
//! The real Orchestrator and the full tool surface land in later slices.

use rmcp::{
    handler::server::router::tool::ToolRouter,
    model::{Implementation, ServerCapabilities, ServerInfo},
    tool, tool_handler, tool_router, ErrorData as McpError, Json, ServerHandler,
};
use schemars::JsonSchema;
use serde::Serialize;

/// Placeholder result for `get_status`. In a later slice this is replaced by the
/// running Instance's live QMP `query-status` (run state of the Guest CPUs); for
/// now it reports the lifecycle state `NONE` (no Instance), mirroring how the TS
/// `get_instance` reports an absent Instance.
#[derive(Debug, Serialize, JsonSchema)]
pub struct PlaceholderStatus {
    /// Lifecycle state of the managed Instance. `NONE` means no Instance is running.
    pub state: String,
    /// A note that this is the slice-1 placeholder, not a real QMP query-status.
    pub note: String,
}

/// The one MCP server struct. Holds its generated [`ToolRouter`]; concurrent tool
/// calls will serialize on the shared Orchestrator once it is introduced.
#[derive(Clone)]
pub struct QmpMcpServer {
    tool_router: ToolRouter<Self>,
}

#[tool_router]
impl QmpMcpServer {
    /// Construct the server, wiring up the tool router generated by `#[tool_router]`.
    pub fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }

    /// Read-only. Placeholder status tool (see [`PlaceholderStatus`]).
    #[tool(
        description = "Return the running QEMU Instance's live QMP query-status result \
                       (run state of the Guest CPUs). Placeholder in this slice: reports \
                       state NONE until the Orchestrator lands."
    )]
    async fn get_status(&self) -> Result<Json<PlaceholderStatus>, McpError> {
        Ok(Json(PlaceholderStatus {
            state: "NONE".to_string(),
            note: "walking skeleton: no Instance is running; real query-status arrives \
                   in a later slice"
                .to_string(),
        }))
    }
}

impl Default for QmpMcpServer {
    fn default() -> Self {
        Self::new()
    }
}

#[tool_handler]
impl ServerHandler for QmpMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            instructions: Some(
                "QEMU MCP server (Rust variant). Build, launch, drive, and tear down a single \
                 QEMU Instance over QMP. This slice exposes only a placeholder get_status tool."
                    .to_string(),
            ),
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            // Advertise our own identity; `Implementation::default()` would report
            // rmcp's crate name/version, so set name + version explicitly.
            server_info: Implementation {
                name: "qmp-mcp".to_string(),
                version: env!("CARGO_PKG_VERSION").to_string(),
                ..Default::default()
            },
            ..Default::default()
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn constructs_and_lists_get_status() {
        let server = QmpMcpServer::new();

        // The tool router advertises exactly the get_status tool.
        assert!(server.tool_router.has_route("get_status"));
        let tools = server.tool_router.list_all();
        assert!(
            tools.iter().any(|t| t.name.as_ref() == "get_status"),
            "get_status missing from {:?}",
            tools.iter().map(|t| t.name.as_ref()).collect::<Vec<_>>()
        );
    }

    #[tokio::test]
    async fn get_info_advertises_identity_and_tools() {
        let info = QmpMcpServer::new().get_info();
        assert_eq!(info.server_info.name, "qmp-mcp");
        assert_eq!(info.server_info.version, env!("CARGO_PKG_VERSION"));
        assert!(
            info.capabilities.tools.is_some(),
            "tools capability must be advertised"
        );
    }
}
